// packages/react/src/index.ts
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

import type { ClientRuntime } from '@zmdb/client';
import { createContext, createElement, useCallback, useContext, useEffect, useRef, useState } from 'react';
import type { DependencyList, ReactElement, ReactNode } from 'react';

export type QueryLoader<Client, Output> = (client: Client, signal: AbortSignal) => PromiseLike<Output>;

export type MutationRunner<Client, Input, Output> = (
  client: Client,
  input: Input,
  signal: AbortSignal,
) => PromiseLike<Output>;

export interface QueryState<Output> {
  readonly data: Output | undefined;
  readonly error: unknown;
  readonly loading: boolean;
  refresh(): Promise<void>;
}

export interface MutationState<Input, Output> {
  readonly error: unknown;
  readonly pending: boolean;
  mutate(input: Input): Promise<Output>;
}

export type ZmdbReactRequestKind = 'mutation' | 'query';

/**
 * Per-provider request observation for official adapters that add an
 * environment lifecycle around the React hooks.
 */
export interface ZmdbReactRequestLifecycle {
  register(kind: ZmdbReactRequestKind, controller: AbortController): (() => void) | void;
}

export interface ZmdbClientProviderProps<Client> {
  readonly client: Client;
  readonly children?: ReactNode;
  readonly requestLifecycle?: ZmdbReactRequestLifecycle;
}

export interface ZmdbReactBindings<Client extends object> {
  ZmdbClientProvider(props: ZmdbClientProviderProps<Client>): ReactElement;
  useZmdbClient(): Client;
  useZmdbQuery<Output>(load: QueryLoader<Client, Output>, dependencies: DependencyList): QueryState<Output>;
  useZmdbMutation<Input, Output>(run: MutationRunner<Client, Input, Output>): MutationState<Input, Output>;
}

interface MissingClient {
  readonly kind: 'missing';
}

interface PresentClient<Client> {
  readonly kind: 'client';
  readonly client: Client;
  readonly requestLifecycle: ZmdbReactRequestLifecycle | undefined;
}

type ClientContextValue<Client> = MissingClient | PresentClient<Client>;

interface QuerySnapshot<Output> {
  readonly data: Output | undefined;
  readonly error: unknown;
  readonly loading: boolean;
}

interface MutationSnapshot {
  readonly error: unknown;
  readonly pending: boolean;
}

const MISSING_CLIENT: MissingClient = Object.freeze({ kind: 'missing' });

function querySnapshot<Output>(): QuerySnapshot<Output> {
  return { data: undefined, error: undefined, loading: false };
}

function mutationSnapshot(): MutationSnapshot {
  return { error: undefined, pending: false };
}

function abort(controller: AbortController | undefined, reason: Error): void {
  if (controller !== undefined && !controller.signal.aborted) controller.abort(reason);
}

function once(cleanup: (() => void) | void): () => void {
  let complete = false;
  return () => {
    if (complete) return;
    complete = true;
    cleanup?.();
  };
}

export function createZmdbReact<Client extends object = ClientRuntime>(
  bindingName = '@zmdb/react',
): ZmdbReactBindings<Client> {
  const ClientContext = createContext<ClientContextValue<Client>>(MISSING_CLIENT);

  function ZmdbClientProvider(props: ZmdbClientProviderProps<Client>): ReactElement {
    return createElement(
      ClientContext.Provider,
      {
        value: {
          kind: 'client',
          client: props.client,
          requestLifecycle: props.requestLifecycle,
        },
      },
      props.children,
    );
  }

  function useClientContext(): PresentClient<Client> {
    const value = useContext(ClientContext);
    if (value.kind === 'client') return value;
    throw new Error(`${bindingName} client is unavailable; render this hook under ${bindingName}.ZmdbClientProvider`);
  }

  function useZmdbClient(): Client {
    return useClientContext().client;
  }

  function useZmdbQuery<Output>(load: QueryLoader<Client, Output>, dependencies: DependencyList): QueryState<Output> {
    const { client, requestLifecycle } = useClientContext();
    const selectedLoad = useCallback(load, dependencies);
    const [snapshot, setSnapshot] = useState<QuerySnapshot<Output>>(querySnapshot);
    const active = useRef(false);
    const generation = useRef(0);
    const controller = useRef<AbortController | undefined>(undefined);
    const unregister = useRef<(() => void) | undefined>(undefined);

    const start = useCallback(
      (clearData: boolean): Promise<void> => {
        if (!active.current) {
          return Promise.reject(new Error(`${bindingName} query is not mounted`));
        }

        generation.current += 1;
        const selectedGeneration = generation.current;
        const previousController = controller.current;
        const previousUnregister = unregister.current;
        controller.current = undefined;
        unregister.current = undefined;
        abort(previousController, new Error(`${bindingName} query was superseded`));
        previousUnregister?.();

        const selectedController = new AbortController();
        const selectedUnregister = once(requestLifecycle?.register('query', selectedController));
        controller.current = selectedController;
        unregister.current = selectedUnregister;
        setSnapshot(previous => ({
          data: clearData ? undefined : previous.data,
          error: undefined,
          loading: true,
        }));

        const onAbort = (): void => {
          if (active.current && generation.current === selectedGeneration) {
            setSnapshot(previous => ({ data: previous.data, error: undefined, loading: false }));
          }
        };
        selectedController.signal.addEventListener('abort', onAbort, { once: true });
        if (selectedController.signal.aborted) onAbort();

        const finish = (): void => {
          selectedController.signal.removeEventListener('abort', onAbort);
          selectedUnregister();
          if (controller.current === selectedController) {
            controller.current = undefined;
            unregister.current = undefined;
          }
        };

        const operation = Promise.resolve().then(() => selectedLoad(client, selectedController.signal));
        return operation.then(
          value => {
            if (active.current && generation.current === selectedGeneration && !selectedController.signal.aborted) {
              setSnapshot({ data: value, error: undefined, loading: false });
            }
            finish();
          },
          error => {
            if (active.current && generation.current === selectedGeneration && !selectedController.signal.aborted) {
              setSnapshot(previous => ({ data: previous.data, error, loading: false }));
            }
            finish();
            throw error;
          },
        );
      },
      [bindingName, client, requestLifecycle, selectedLoad],
    );

    useEffect(() => {
      active.current = true;
      void start(true).catch(() => undefined);
      return () => {
        active.current = false;
        generation.current += 1;
        const selectedController = controller.current;
        const selectedUnregister = unregister.current;
        controller.current = undefined;
        unregister.current = undefined;
        abort(selectedController, new Error(`${bindingName} query owner was disposed`));
        selectedUnregister?.();
      };
    }, [bindingName, start]);

    const refresh = useCallback(() => start(false), [start]);
    return { ...snapshot, refresh };
  }

  function useZmdbMutation<Input, Output>(run: MutationRunner<Client, Input, Output>): MutationState<Input, Output> {
    const { client, requestLifecycle } = useClientContext();
    const [snapshot, setSnapshot] = useState<MutationSnapshot>(mutationSnapshot);
    const active = useRef(false);
    const pending = useRef(0);
    const newest = useRef(0);
    const controllers = useRef(new Map<AbortController, () => void>());

    useEffect(() => {
      active.current = true;
      return () => {
        active.current = false;
        for (const [selectedController, selectedUnregister] of controllers.current) {
          abort(selectedController, new Error(`${bindingName} mutation owner was disposed`));
          selectedUnregister();
        }
        controllers.current.clear();
      };
    }, [bindingName]);

    const mutate = useCallback(
      (input: Input): Promise<Output> => {
        if (!active.current) {
          return Promise.reject(new Error(`${bindingName} mutation is not mounted`));
        }

        newest.current += 1;
        const selectedGeneration = newest.current;
        const selectedController = new AbortController();
        const selectedUnregister = once(requestLifecycle?.register('mutation', selectedController));
        controllers.current.set(selectedController, selectedUnregister);
        pending.current += 1;
        setSnapshot({ error: undefined, pending: true });

        const finish = (): void => {
          controllers.current.delete(selectedController);
          selectedUnregister();
          pending.current -= 1;
        };

        const operation = Promise.resolve().then(() => run(client, input, selectedController.signal));
        return operation.then(
          value => {
            finish();
            if (active.current) {
              setSnapshot(previous => ({ error: previous.error, pending: pending.current > 0 }));
            }
            return value;
          },
          error => {
            finish();
            if (active.current) {
              setSnapshot(previous => ({
                error:
                  selectedGeneration === newest.current && !selectedController.signal.aborted ? error : previous.error,
                pending: pending.current > 0,
              }));
            }
            throw error;
          },
        );
      },
      [bindingName, client, requestLifecycle, run],
    );

    return { ...snapshot, mutate };
  }

  return Object.freeze({
    ZmdbClientProvider,
    useZmdbClient,
    useZmdbQuery,
    useZmdbMutation,
  });
}

// packages/angular/src/index.ts
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

import { DestroyRef, InjectionToken, inject, makeEnvironmentProviders, signal } from '@angular/core';
import type { EnvironmentProviders, Signal } from '@angular/core';
import { Observable } from 'rxjs';

export type QueryLoader<Client, Input, Output> = (
  client: Client,
  input: Input,
  signal: AbortSignal,
) => PromiseLike<Output>;

export type MutationRunner<Client, Input, Output> = (
  client: Client,
  input: Input,
  signal: AbortSignal,
) => PromiseLike<Output>;

export interface ZmdbSignalQuery<Input, Output> {
  readonly data: Signal<Output | undefined>;
  readonly error: Signal<unknown>;
  readonly loading: Signal<boolean>;
  setInput(input: Input): void;
  refresh(): Promise<void>;
}

export interface ZmdbSignalMutation<Input, Output> {
  readonly error: Signal<unknown>;
  readonly pending: Signal<boolean>;
  mutate(input: Input): Promise<Output>;
}

export interface ZmdbClientRef<Client> {
  readonly client: Client;
}

export interface ZmdbAngularBindings<Client> {
  readonly ZMDB_CLIENT: InjectionToken<ZmdbClientRef<Client>>;
  provideZmdbClient(client: Client): EnvironmentProviders;
  injectZmdbClient(): Client;
  zmdbQuery<Input, Output>(input: Input, load: QueryLoader<Client, Input, Output>): ZmdbSignalQuery<Input, Output>;
  zmdbMutation<Input, Output>(run: MutationRunner<Client, Input, Output>): ZmdbSignalMutation<Input, Output>;
  zmdbObservable<Input, Output>(input: Input, load: QueryLoader<Client, Input, Output>): Observable<Output>;
}

function invoke<Client, Input, Output>(
  load: QueryLoader<Client, Input, Output>,
  client: Client,
  input: Input,
  abortSignal: AbortSignal,
): Promise<Output> {
  try {
    return Promise.resolve(load(client, input, abortSignal));
  } catch (error) {
    return Promise.reject(error);
  }
}

function cancellation(action: string): Error {
  const error = new Error(`@zmdb/angular ${action}`);
  error.name = 'ZmdbAngularCancellation';
  return error;
}

function signalQuery<Client, Input, Output>(
  token: InjectionToken<ZmdbClientRef<Client>>,
  initialInput: Input,
  load: QueryLoader<Client, Input, Output>,
): ZmdbSignalQuery<Input, Output> {
  const client = inject(token).client;
  const destroyRef = inject(DestroyRef);
  const data = signal<Output | undefined>(undefined);
  const error = signal<unknown>(undefined);
  const loading = signal(false);
  let input = initialInput;
  let generation = 0;
  let active: AbortController | undefined;
  let destroyed = false;

  const start = (): Promise<void> => {
    if (destroyed) return Promise.reject(cancellation('query started after its injector was destroyed'));

    generation += 1;
    const selectedGeneration = generation;
    active?.abort(cancellation('query superseded'));
    const controller = new AbortController();
    active = controller;
    error.set(undefined);
    loading.set(true);

    return invoke(load, client, input, controller.signal).then(
      value => {
        if (!destroyed && selectedGeneration === generation) {
          data.set(value);
          error.set(undefined);
          loading.set(false);
        }
        if (active === controller) active = undefined;
      },
      failure => {
        if (!destroyed && selectedGeneration === generation && !controller.signal.aborted) {
          error.set(failure);
          loading.set(false);
        }
        if (active === controller) active = undefined;
        throw failure;
      },
    );
  };

  const startSilently = (): void => {
    void start().catch(() => undefined);
  };

  destroyRef.onDestroy(() => {
    if (destroyed) return;
    destroyed = true;
    generation += 1;
    const controller = active;
    active = undefined;
    controller?.abort(cancellation('query owner destroyed'));
    loading.set(false);
  });

  startSilently();

  return Object.freeze({
    data: data.asReadonly(),
    error: error.asReadonly(),
    loading: loading.asReadonly(),
    setInput(nextInput: Input): void {
      if (destroyed) throw cancellation('query input changed after its injector was destroyed');
      if (Object.is(input, nextInput)) return;
      input = nextInput;
      data.set(undefined);
      error.set(undefined);
      startSilently();
    },
    refresh: start,
  });
}

function signalMutation<Client, Input, Output>(
  token: InjectionToken<ZmdbClientRef<Client>>,
  run: MutationRunner<Client, Input, Output>,
): ZmdbSignalMutation<Input, Output> {
  const client = inject(token).client;
  const destroyRef = inject(DestroyRef);
  const error = signal<unknown>(undefined);
  const pending = signal(false);
  const controllers = new Set<AbortController>();
  let inFlight = 0;
  let generation = 0;
  let destroyed = false;

  destroyRef.onDestroy(() => {
    if (destroyed) return;
    destroyed = true;
    const reason = cancellation('mutation owner destroyed');
    for (const controller of controllers) controller.abort(reason);
    controllers.clear();
    inFlight = 0;
    pending.set(false);
  });

  return Object.freeze({
    error: error.asReadonly(),
    pending: pending.asReadonly(),
    mutate(input: Input): Promise<Output> {
      if (destroyed) return Promise.reject(cancellation('mutation started after its injector was destroyed'));

      generation += 1;
      const selectedGeneration = generation;
      const controller = new AbortController();
      controllers.add(controller);
      inFlight += 1;
      error.set(undefined);
      pending.set(true);

      const finish = (): void => {
        controllers.delete(controller);
        if (destroyed) return;
        inFlight -= 1;
        pending.set(inFlight > 0);
      };

      return invoke(run, client, input, controller.signal).then(
        value => {
          finish();
          return value;
        },
        failure => {
          finish();
          if (!destroyed && selectedGeneration === generation && !controller.signal.aborted) {
            error.set(failure);
          }
          throw failure;
        },
      );
    },
  });
}

function queryObservable<Client, Input, Output>(
  token: InjectionToken<ZmdbClientRef<Client>>,
  input: Input,
  load: QueryLoader<Client, Input, Output>,
): Observable<Output> {
  const client = inject(token).client;
  const destroyRef = inject(DestroyRef);

  return new Observable<Output>(subscriber => {
    if (destroyRef.destroyed) {
      subscriber.complete();
      return;
    }

    const controller = new AbortController();
    let active = true;
    const unregister = destroyRef.onDestroy(() => {
      if (!active) return;
      active = false;
      controller.abort(cancellation('Observable owner destroyed'));
      subscriber.complete();
    });

    void invoke(load, client, input, controller.signal).then(
      value => {
        if (!active) return;
        active = false;
        unregister();
        subscriber.next(value);
        subscriber.complete();
      },
      failure => {
        if (!active) return;
        active = false;
        unregister();
        subscriber.error(failure);
      },
    );

    return () => {
      unregister();
      if (!active) return;
      active = false;
      controller.abort(cancellation('Observable unsubscribed'));
    };
  });
}

export function createZmdbAngular<Client>(
  description: string = '@zmdb/angular generated client',
): ZmdbAngularBindings<Client> {
  const ZMDB_CLIENT = new InjectionToken<ZmdbClientRef<Client>>(description);

  const provideZmdbClient = (client: Client): EnvironmentProviders =>
    makeEnvironmentProviders([{ provide: ZMDB_CLIENT, useValue: Object.freeze({ client }) }]);

  const injectZmdbClient = (): Client => inject(ZMDB_CLIENT).client;

  return Object.freeze({
    ZMDB_CLIENT,
    provideZmdbClient,
    injectZmdbClient,
    zmdbQuery<Input, Output>(input: Input, load: QueryLoader<Client, Input, Output>): ZmdbSignalQuery<Input, Output> {
      return signalQuery(ZMDB_CLIENT, input, load);
    },
    zmdbMutation<Input, Output>(run: MutationRunner<Client, Input, Output>): ZmdbSignalMutation<Input, Output> {
      return signalMutation(ZMDB_CLIENT, run);
    },
    zmdbObservable<Input, Output>(input: Input, load: QueryLoader<Client, Input, Output>): Observable<Output> {
      return queryObservable(ZMDB_CLIENT, input, load);
    },
  });
}
