// packages/solid/src/index.ts
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

import type { CallOptions } from '@zmdb/client';
import {
  createComponent,
  createContext,
  createMemo,
  createResource,
  createSignal,
  getOwner,
  onCleanup,
  useContext,
} from 'solid-js';
import type { Accessor, FlowComponent, Resource } from 'solid-js';

export type AdapterSignal = Exclude<CallOptions['signal'], undefined>;

export type QueryLoader<Client, Input, Output> = (
  client: Client,
  input: Input,
  signal: AdapterSignal,
) => PromiseLike<Output>;

export type MutationRunner<Client, Input, Output> = (
  client: Client,
  input: Input,
  signal: AdapterSignal,
) => PromiseLike<Output>;

export type SolidQuerySource<Input> = Input | Accessor<Input>;

export interface SolidQuery<Output> {
  /** Native Solid resource: reads participate in Suspense and throw the original error. */
  readonly data: Resource<Output | undefined>;
  /** Last successful value without reading through an errored resource. */
  readonly latest: Accessor<Output | undefined>;
  readonly error: Accessor<unknown>;
  readonly loading: Accessor<boolean>;
  /** Exact loader result currently owned by the resource. */
  readonly pending: Accessor<PromiseLike<Output> | undefined>;
  refresh(): Promise<void>;
}

export interface SolidMutation<Input, Output> {
  readonly error: Accessor<unknown>;
  readonly pending: Accessor<boolean>;
  mutate(input: Input): Promise<Output>;
}

export interface ZmdbSolidBindings<Client> {
  readonly Provider: FlowComponent<{ readonly client: Client }>;
  useClient(): Client;
  query<Input, Output>(source: SolidQuerySource<Input>, load: QueryLoader<Client, Input, Output>): SolidQuery<Output>;
  mutation<Input, Output>(run: MutationRunner<Client, Input, Output>): SolidMutation<Input, Output>;
}

function requireOwner(primitive: string): void {
  if (getOwner() === null) {
    throw new Error(`@zmdb/solid ${primitive} must be created under a Solid owner`);
  }
}

function sourceAccessor<Input>(source: SolidQuerySource<Input>): Accessor<Input> {
  if (typeof source === 'function') return () => Reflect.apply(source, undefined, []);
  return () => source;
}

function promiseForSolid<Value>(operation: PromiseLike<Value>): Promise<Value> {
  return operation instanceof Promise ? operation : Promise.resolve(operation);
}

export function createZmdbSolid<Client>(): ZmdbSolidBindings<Client> {
  const ClientContext = createContext<Client>();

  const Provider: FlowComponent<{ readonly client: Client }> = props =>
    createComponent(ClientContext.Provider, {
      value: props.client,
      get children() {
        return props.children;
      },
    });

  function useClient(): Client {
    const client = useContext(ClientContext);
    if (client === undefined) throw new Error('@zmdb/solid client is unavailable outside its Provider');
    return client;
  }

  function query<Input, Output>(
    source: SolidQuerySource<Input>,
    load: QueryLoader<Client, Input, Output>,
  ): SolidQuery<Output> {
    requireOwner('query');
    const client = useClient();
    const readSource = sourceAccessor(source);
    const [latest, setLatest] = createSignal<Output>();
    const [pending, setPending] = createSignal<PromiseLike<Output>>();
    let controller: AbortController | undefined;
    let generation = 0;
    let previousInput: Input | undefined;
    let hasPreviousInput = false;

    const [data, actions] = createResource<Output, Input>(readSource, input => {
      const changed = hasPreviousInput && !Object.is(previousInput, input);
      previousInput = input;
      hasPreviousInput = true;
      if (changed) setLatest(() => undefined);

      controller?.abort(new Error('@zmdb/solid query superseded'));
      const currentController = new AbortController();
      controller = currentController;
      const currentGeneration = ++generation;
      const operation = load(client, input, currentController.signal);
      const solidOperation = promiseForSolid(operation);
      setPending(() => operation);
      void Promise.resolve(operation).then(
        value => {
          if (currentGeneration === generation && !currentController.signal.aborted) setLatest(() => value);
          if (currentGeneration === generation) setPending(() => undefined);
        },
        () => {
          if (currentGeneration === generation) setPending(() => undefined);
        },
      );
      return solidOperation;
    });

    onCleanup(() => {
      generation++;
      controller?.abort(new Error('@zmdb/solid query owner disposed'));
      setPending(() => undefined);
    });

    return {
      data,
      latest,
      error: () => data.error,
      loading: () => data.loading,
      pending,
      async refresh() {
        actions.refetch();
        const operation = pending();
        if (operation !== undefined) await operation;
      },
    };
  }

  function mutation<Input, Output>(run: MutationRunner<Client, Input, Output>): SolidMutation<Input, Output> {
    requireOwner('mutation');
    const client = useClient();
    const [error, setError] = createSignal<unknown>(undefined);
    const [activeCount, setActiveCount] = createSignal(0);
    const pending = createMemo(() => activeCount() > 0);
    const controllers = new Set<AbortController>();
    let generation = 0;
    let active = true;

    onCleanup(() => {
      active = false;
      generation++;
      for (const controller of controllers) {
        controller.abort(new Error('@zmdb/solid mutation owner disposed'));
      }
      controllers.clear();
    });

    return {
      error,
      pending,
      mutate(input) {
        if (!active) return Promise.reject(new Error('@zmdb/solid mutation owner is disposed'));
        const controller = new AbortController();
        const currentGeneration = ++generation;
        controllers.add(controller);
        setActiveCount(count => count + 1);
        setError(() => undefined);

        let operation: PromiseLike<Output>;
        try {
          operation = run(client, input, controller.signal);
        } catch (caught) {
          operation = Promise.reject(caught);
        }

        return Promise.resolve(operation).then(
          value => {
            if (controllers.delete(controller) && active) setActiveCount(count => count - 1);
            return value;
          },
          caught => {
            if (controllers.delete(controller) && active) setActiveCount(count => count - 1);
            if (active && currentGeneration === generation && !controller.signal.aborted) setError(() => caught);
            throw caught;
          },
        );
      },
    };
  }

  return Object.freeze({ Provider, useClient, query, mutation });
}

// packages/react/src/index.ts
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

import type { ClientRuntime } from '@zmdb/client';
import { createContext, createElement, useCallback, useContext, useEffect, useRef, useState } from 'react';
import type { DependencyList, ReactElement, ReactNode } from 'react';

export type QueryLoader<Client, Output> = (client: Client, signal: AbortSignal) => PromiseLike<Output>;

export type MutationRunner<Client, Input, Output> = (
  client: Client,
  input: Input,
  signal: AbortSignal,
) => PromiseLike<Output>;

export interface QueryState<Output> {
  readonly data: Output | undefined;
  readonly error: unknown;
  readonly loading: boolean;
  refresh(): Promise<void>;
}

export interface MutationState<Input, Output> {
  readonly error: unknown;
  readonly pending: boolean;
  mutate(input: Input): Promise<Output>;
}

export type ZmdbReactRequestKind = 'mutation' | 'query';

/**
 * Per-provider request observation for official adapters that add an
 * environment lifecycle around the React hooks.
 */
export interface ZmdbReactRequestLifecycle {
  register(kind: ZmdbReactRequestKind, controller: AbortController): (() => void) | void;
}

export interface ZmdbClientProviderProps<Client> {
  readonly client: Client;
  readonly children?: ReactNode;
  readonly requestLifecycle?: ZmdbReactRequestLifecycle;
}

export interface ZmdbReactBindings<Client extends object> {
  ZmdbClientProvider(props: ZmdbClientProviderProps<Client>): ReactElement;
  useZmdbClient(): Client;
  useZmdbQuery<Output>(load: QueryLoader<Client, Output>, dependencies: DependencyList): QueryState<Output>;
  useZmdbMutation<Input, Output>(run: MutationRunner<Client, Input, Output>): MutationState<Input, Output>;
}

interface MissingClient {
  readonly kind: 'missing';
}

interface PresentClient<Client> {
  readonly kind: 'client';
  readonly client: Client;
  readonly requestLifecycle: ZmdbReactRequestLifecycle | undefined;
}

type ClientContextValue<Client> = MissingClient | PresentClient<Client>;

interface QuerySnapshot<Output> {
  readonly data: Output | undefined;
  readonly error: unknown;
  readonly loading: boolean;
}

interface MutationSnapshot {
  readonly error: unknown;
  readonly pending: boolean;
}

const MISSING_CLIENT: MissingClient = Object.freeze({ kind: 'missing' });

function querySnapshot<Output>(): QuerySnapshot<Output> {
  return { data: undefined, error: undefined, loading: false };
}

function mutationSnapshot(): MutationSnapshot {
  return { error: undefined, pending: false };
}

function abort(controller: AbortController | undefined, reason: Error): void {
  if (controller !== undefined && !controller.signal.aborted) controller.abort(reason);
}

function once(cleanup: (() => void) | void): () => void {
  let complete = false;
  return () => {
    if (complete) return;
    complete = true;
    cleanup?.();
  };
}

export function createZmdbReact<Client extends object = ClientRuntime>(
  bindingName = '@zmdb/react',
): ZmdbReactBindings<Client> {
  const ClientContext = createContext<ClientContextValue<Client>>(MISSING_CLIENT);

  function ZmdbClientProvider(props: ZmdbClientProviderProps<Client>): ReactElement {
    return createElement(
      ClientContext.Provider,
      {
        value: {
          kind: 'client',
          client: props.client,
          requestLifecycle: props.requestLifecycle,
        },
      },
      props.children,
    );
  }

  function useClientContext(): PresentClient<Client> {
    const value = useContext(ClientContext);
    if (value.kind === 'client') return value;
    throw new Error(`${bindingName} client is unavailable; render this hook under ${bindingName}.ZmdbClientProvider`);
  }

  function useZmdbClient(): Client {
    return useClientContext().client;
  }

  function useZmdbQuery<Output>(load: QueryLoader<Client, Output>, dependencies: DependencyList): QueryState<Output> {
    const { client, requestLifecycle } = useClientContext();
    const selectedLoad = useCallback(load, dependencies);
    const [snapshot, setSnapshot] = useState<QuerySnapshot<Output>>(querySnapshot);
    const active = useRef(false);
    const generation = useRef(0);
    const controller = useRef<AbortController | undefined>(undefined);
    const unregister = useRef<(() => void) | undefined>(undefined);

    const start = useCallback(
      (clearData: boolean): Promise<void> => {
        if (!active.current) {
          return Promise.reject(new Error(`${bindingName} query is not mounted`));
        }

        generation.current += 1;
        const selectedGeneration = generation.current;
        const previousController = controller.current;
        const previousUnregister = unregister.current;
        controller.current = undefined;
        unregister.current = undefined;
        abort(previousController, new Error(`${bindingName} query was superseded`));
        previousUnregister?.();

        const selectedController = new AbortController();
        const selectedUnregister = once(requestLifecycle?.register('query', selectedController));
        controller.current = selectedController;
        unregister.current = selectedUnregister;
        setSnapshot(previous => ({
          data: clearData ? undefined : previous.data,
          error: undefined,
          loading: true,
        }));

        const onAbort = (): void => {
          if (active.current && generation.current === selectedGeneration) {
            setSnapshot(previous => ({ data: previous.data, error: undefined, loading: false }));
          }
        };
        selectedController.signal.addEventListener('abort', onAbort, { once: true });
        if (selectedController.signal.aborted) onAbort();

        const finish = (): void => {
          selectedController.signal.removeEventListener('abort', onAbort);
          selectedUnregister();
          if (controller.current === selectedController) {
            controller.current = undefined;
            unregister.current = undefined;
          }
        };

        const operation = Promise.resolve().then(() => selectedLoad(client, selectedController.signal));
        return operation.then(
          value => {
            if (active.current && generation.current === selectedGeneration && !selectedController.signal.aborted) {
              setSnapshot({ data: value, error: undefined, loading: false });
            }
            finish();
          },
          error => {
            if (active.current && generation.current === selectedGeneration && !selectedController.signal.aborted) {
              setSnapshot(previous => ({ data: previous.data, error, loading: false }));
            }
            finish();
            throw error;
          },
        );
      },
      [bindingName, client, requestLifecycle, selectedLoad],
    );

    useEffect(() => {
      active.current = true;
      void start(true).catch(() => undefined);
      return () => {
        active.current = false;
        generation.current += 1;
        const selectedController = controller.current;
        const selectedUnregister = unregister.current;
        controller.current = undefined;
        unregister.current = undefined;
        abort(selectedController, new Error(`${bindingName} query owner was disposed`));
        selectedUnregister?.();
      };
    }, [bindingName, start]);

    const refresh = useCallback(() => start(false), [start]);
    return { ...snapshot, refresh };
  }

  function useZmdbMutation<Input, Output>(run: MutationRunner<Client, Input, Output>): MutationState<Input, Output> {
    const { client, requestLifecycle } = useClientContext();
    const [snapshot, setSnapshot] = useState<MutationSnapshot>(mutationSnapshot);
    const active = useRef(false);
    const pending = useRef(0);
    const newest = useRef(0);
    const controllers = useRef(new Map<AbortController, () => void>());

    useEffect(() => {
      active.current = true;
      return () => {
        active.current = false;
        for (const [selectedController, selectedUnregister] of controllers.current) {
          abort(selectedController, new Error(`${bindingName} mutation owner was disposed`));
          selectedUnregister();
        }
        controllers.current.clear();
      };
    }, [bindingName]);

    const mutate = useCallback(
      (input: Input): Promise<Output> => {
        if (!active.current) {
          return Promise.reject(new Error(`${bindingName} mutation is not mounted`));
        }

        newest.current += 1;
        const selectedGeneration = newest.current;
        const selectedController = new AbortController();
        const selectedUnregister = once(requestLifecycle?.register('mutation', selectedController));
        controllers.current.set(selectedController, selectedUnregister);
        pending.current += 1;
        setSnapshot({ error: undefined, pending: true });

        const finish = (): void => {
          controllers.current.delete(selectedController);
          selectedUnregister();
          pending.current -= 1;
        };

        const operation = Promise.resolve().then(() => run(client, input, selectedController.signal));
        return operation.then(
          value => {
            finish();
            if (active.current) {
              setSnapshot(previous => ({ error: previous.error, pending: pending.current > 0 }));
            }
            return value;
          },
          error => {
            finish();
            if (active.current) {
              setSnapshot(previous => ({
                error:
                  selectedGeneration === newest.current && !selectedController.signal.aborted ? error : previous.error,
                pending: pending.current > 0,
              }));
            }
            throw error;
          },
        );
      },
      [bindingName, client, requestLifecycle, run],
    );

    return { ...snapshot, mutate };
  }

  return Object.freeze({
    ZmdbClientProvider,
    useZmdbClient,
    useZmdbQuery,
    useZmdbMutation,
  });
}
