// fixtures/client-adapters/src/solid-binding.ts
import { createZmdbSolid, type SolidMutation, type SolidQuery } from '@zmdb/client/solid';
import { createComponent, createRoot, createSignal, Suspense } from 'solid-js';
import { renderToStringAsync } from 'solid-js/web';

import type {
  AdapterConformanceBinding,
  ConformanceMutation,
  ConformanceQuery,
  MutationRunner,
  MutationSnapshot,
  QueryLoader,
  QuerySnapshot,
} from './conformance.js';
import { ADAPTER_PACKAGES } from './package-matrix.js';

function solidPackageExpectation() {
  const expectation = ADAPTER_PACKAGES.find(candidate => candidate.name === '@zmdb/client/solid');
  if (expectation === undefined) throw new Error('missing @zmdb/client/solid package expectation');
  return expectation;
}

const SOLID_PACKAGE = solidPackageExpectation();

function requireValue<Value>(value: Value | undefined, label: string): Value {
  if (value === undefined) throw new Error(`Solid conformance ${label} is unavailable before mount`);
  return value;
}

async function settle(loading: () => boolean): Promise<void> {
  for (let attempt = 0; attempt < 1_000; attempt++) {
    if (!loading()) return;
    await new Promise<void>(resolve => {
      setImmediate(resolve);
    });
  }
  throw new Error('Solid conformance request did not settle');
}

function prepareSolidQuery<Client, Input, Output>(options: {
  readonly client: Client;
  readonly input: Input;
  readonly load: QueryLoader<Client, Input, Output>;
}): ConformanceQuery<Input, Output> {
  let query: SolidQuery<Output> | undefined;
  let updateInput: ((input: Input) => void) | undefined;
  let dispose: (() => void) | undefined;
  let mounted = false;

  return {
    snapshot(): QuerySnapshot<Output> {
      if (!mounted) return { data: undefined, error: undefined, loading: false };
      const current = requireValue(query, 'query');
      return { data: current.latest(), error: current.error(), loading: current.loading() };
    },
    async mount() {
      if (mounted) throw new Error('Solid conformance query mounted twice');
      mounted = true;
      dispose = createRoot(disposeRoot => {
        const [inputBox, setInputBox] = createSignal({ value: options.input }, { equals: false });
        updateInput = input => {
          setInputBox({ value: input });
        };
        const bindings = createZmdbSolid<Client>();
        createComponent(bindings.Provider, {
          client: options.client,
          get children() {
            query = bindings.query(() => inputBox().value, options.load);
            return undefined;
          },
        });
        return disposeRoot;
      });
    },
    async update(input) {
      requireValue(updateInput, 'input setter')(input);
      await Promise.resolve();
    },
    async refresh() {
      await requireValue(query, 'query').refresh();
    },
    async whenSettled() {
      await settle(requireValue(query, 'query').loading);
    },
    async dispose() {
      dispose?.();
      dispose = undefined;
    },
  };
}

function prepareSolidMutation<Client, Input, Output>(options: {
  readonly client: Client;
  readonly run: MutationRunner<Client, Input, Output>;
}): ConformanceMutation<Input, Output> {
  let mutation: SolidMutation<Input, Output> | undefined;
  let dispose: (() => void) | undefined;
  let mounted = false;

  return {
    snapshot(): MutationSnapshot {
      if (!mounted) return { error: undefined, pending: false };
      const current = requireValue(mutation, 'mutation');
      return { error: current.error(), pending: current.pending() };
    },
    async mount() {
      if (mounted) throw new Error('Solid conformance mutation mounted twice');
      mounted = true;
      dispose = createRoot(disposeRoot => {
        const bindings = createZmdbSolid<Client>();
        createComponent(bindings.Provider, {
          client: options.client,
          get children() {
            mutation = bindings.mutation(options.run);
            return undefined;
          },
        });
        return disposeRoot;
      });
    },
    mutate(input) {
      return requireValue(mutation, 'mutation').mutate(input);
    },
    async dispose() {
      dispose?.();
      dispose = undefined;
    },
  };
}

async function runSolidSsrQuery<Client, Input, Output>(options: {
  readonly client: Client;
  readonly input: Input;
  readonly load: QueryLoader<Client, Input, Output>;
}): Promise<Output> {
  const bindings = createZmdbSolid<Client>();
  let query: SolidQuery<Output> | undefined;
  let operation: PromiseLike<Output> | undefined;

  await renderToStringAsync(() =>
    createComponent(bindings.Provider, {
      client: options.client,
      get children() {
        query = bindings.query(options.input, options.load);
        operation = query.pending();
        return createComponent(Suspense, {
          fallback: '',
          get children() {
            query?.data();
            return '';
          },
        });
      },
    }),
  );

  const current = requireValue(query, 'SSR query');
  const value = await requireValue(operation, 'SSR query operation');
  if (!Object.is(current.latest(), value)) {
    throw new Error('Solid SSR resource did not publish its request-local result');
  }
  return value;
}

export function createSolidAdapterBinding<Client>(): AdapterConformanceBinding<Client> {
  return {
    package: SOLID_PACKAGE,
    prepareQuery(options) {
      return prepareSolidQuery(options);
    },
    prepareMutation(options) {
      return prepareSolidMutation(options);
    },
    runSsrQuery(options) {
      return runSolidSsrQuery(options);
    },
  };
}

// fixtures/client-adapters/src/angular-binding.ts
import { Injector, createEnvironmentInjector, runInInjectionContext } from '@angular/core';
import type { EnvironmentInjector } from '@angular/core';
import { createZmdbAngular } from '@zmdb/client/angular';

import type {
  AdapterConformanceBinding,
  ConformanceMutation,
  ConformanceQuery,
  MutationRunner,
  QueryLoader,
  QuerySnapshot,
} from './conformance.js';
import type { AdapterPackageExpectation } from './package-matrix.js';

function missing(primitive: string): Error {
  return new Error(`@zmdb/client/angular ${primitive} conformance driver is not mounted`);
}

function parentInjector(name: string): EnvironmentInjector {
  return createEnvironmentInjector([], Injector.NULL as EnvironmentInjector, `${name}-parent`);
}

export function createAngularConformanceBinding<Client>(
  packageExpectation: AdapterPackageExpectation,
): AdapterConformanceBinding<Client> {
  const bindings = createZmdbAngular<Client>('adapter conformance client');

  return {
    package: packageExpectation,
    prepareQuery<Input, Output>(options: {
      readonly client: Client;
      readonly input: Input;
      readonly load: QueryLoader<Client, Input, Output>;
    }): ConformanceQuery<Input, Output> {
      let query:
        | {
            readonly data: () => Output | undefined;
            readonly error: () => unknown;
            readonly loading: () => boolean;
            setInput(input: Input): void;
            refresh(): Promise<void>;
          }
        | undefined;
      let latestSettlement = Promise.resolve();
      let parent: EnvironmentInjector | undefined;
      let owner: EnvironmentInjector | undefined;
      let mounted = false;
      let disposed = false;

      const current = () => {
        if (query === undefined) throw missing('query');
        return query;
      };

      const load = (client: Client, input: Input, signal: AbortSignal): Promise<Output> => {
        const operation = Promise.resolve(options.load(client, input, signal));
        latestSettlement = operation.then(
          () => undefined,
          () => undefined,
        );
        return operation;
      };

      return {
        snapshot(): QuerySnapshot<Output> {
          if (query === undefined) return { data: undefined, error: undefined, loading: false };
          return {
            data: query.data(),
            error: query.error(),
            loading: query.loading(),
          };
        },
        async mount(): Promise<void> {
          if (mounted) throw new Error('@zmdb/client/angular query conformance driver mounted twice');
          if (disposed) throw new Error('@zmdb/client/angular query conformance driver mounted after disposal');
          parent = parentInjector('adapter-query');
          owner = createEnvironmentInjector(
            [bindings.provideZmdbClient(options.client)],
            parent,
            'adapter-query-owner',
          );
          query = runInInjectionContext(owner, () => bindings.zmdbQuery(options.input, load));
          mounted = true;
        },
        async update(input: Input): Promise<void> {
          current().setInput(input);
        },
        refresh(): Promise<void> {
          return current().refresh();
        },
        whenSettled(): Promise<void> {
          if (!mounted) return Promise.reject(missing('query'));
          return latestSettlement;
        },
        async dispose(): Promise<void> {
          if (disposed) return;
          disposed = true;
          owner?.destroy();
          parent?.destroy();
        },
      };
    },
    prepareMutation<Input, Output>(options: {
      readonly client: Client;
      readonly run: MutationRunner<Client, Input, Output>;
    }): ConformanceMutation<Input, Output> {
      let mutation:
        | {
            readonly error: () => unknown;
            readonly pending: () => boolean;
            mutate(input: Input): Promise<Output>;
          }
        | undefined;
      let parent: EnvironmentInjector | undefined;
      let owner: EnvironmentInjector | undefined;
      let mounted = false;
      let disposed = false;

      const current = () => {
        if (mutation === undefined) throw missing('mutation');
        return mutation;
      };

      return {
        snapshot() {
          if (mutation === undefined) return { error: undefined, pending: false };
          return { error: mutation.error(), pending: mutation.pending() };
        },
        async mount(): Promise<void> {
          if (mounted) throw new Error('@zmdb/client/angular mutation conformance driver mounted twice');
          if (disposed) throw new Error('@zmdb/client/angular mutation conformance driver mounted after disposal');
          parent = parentInjector('adapter-mutation');
          owner = createEnvironmentInjector(
            [bindings.provideZmdbClient(options.client)],
            parent,
            'adapter-mutation-owner',
          );
          mutation = runInInjectionContext(owner, () => bindings.zmdbMutation(options.run));
          mounted = true;
        },
        mutate(input: Input): Promise<Output> {
          return current().mutate(input);
        },
        async dispose(): Promise<void> {
          if (disposed) return;
          disposed = true;
          owner?.destroy();
          parent?.destroy();
        },
      };
    },
    runSsrQuery<Input, Output>(options: {
      readonly client: Client;
      readonly input: Input;
      readonly load: QueryLoader<Client, Input, Output>;
    }): Promise<Output> {
      const parent = parentInjector('adapter-ssr');
      const owner = createEnvironmentInjector(
        [bindings.provideZmdbClient(options.client)],
        parent,
        'adapter-ssr-request',
      );
      const operation = new Promise<Output>((resolve, reject) => {
        runInInjectionContext(owner, () => {
          bindings.zmdbQuery(options.input, (client, input, signal) => {
            const result = Promise.resolve(options.load(client, input, signal));
            void result.then(resolve, reject);
            return result;
          });
        });
      });
      return operation.finally(() => {
        owner.destroy();
        parent.destroy();
      });
    },
  };
}
